# Generated by Django 3.0.5 on 2020-10-29 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(default='dog', max_length=10, verbose_name='вид')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Виды',
            },
        ),
        migrations.CreateModel(
            name='breed_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=100, verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Порода кошки',
                'verbose_name_plural': 'Порода кошек',
            },
        ),
        migrations.CreateModel(
            name='breed_dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=100, verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Порода собаки',
                'verbose_name_plural': 'Порода собак',
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Услуга', max_length=255, verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
            },
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=14, verbose_name='Номер телефона')),
                ('pet_size', models.PositiveIntegerField(default=10, verbose_name='Весь животного')),
                ('birthday', models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='день рождения')),
                ('vizits', models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='день визита')),
                ('breed_cat', models.ManyToManyField(blank=True, related_name='breed_cat', to='vetsapp.breed_cat', verbose_name='Порода кошки')),
                ('breed_dog', models.ManyToManyField(blank=True, related_name='breed_dog', to='vetsapp.breed_dog', verbose_name='Порода собаки')),
                ('service_pet', models.ForeignKey(default='Услуга', on_delete=django.db.models.deletion.PROTECT, to='vetsapp.service', verbose_name='услуги')),
                ('species', models.ForeignKey(blank=True, default='Вид животного', on_delete=django.db.models.deletion.PROTECT, to='vetsapp.animal', verbose_name='Вид животного')),
                ('user', models.OneToOneField(blank=True, default='Пользователь', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
