# Generated by Django 3.0.5 on 2020-10-31 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_create',
            field=models.DateTimeField(default='', verbose_name='Дата заявки'),
            preserve_default=False,
        ),
    ]
